Update figures, change parameters
guruucsd/DifferentialEncoding pull request #101
Opened 2017-02-18 23:16 UTC by vishaalprasad

This is either to be consistent with COGSCI 2017 submission or to improve on it. Plus a few bug fixes relating to the plots.

2017-02-18 23:32 UTC, vishaalprasad commented
![overall](https://cloud.githubusercontent.com/assets/7337790/23097695/54c53d1c-f5ef-11e6-8849-3d2cea74d273.png)

Here's how the new graph looks. Y-axis are equally scaled (on relative, not absolute, terms) and clearly delineated. Error bars are also cleaner.

2017-02-18 23:35 UTC, bcipolli requested changes
Requested a few changes, lemme know if you have questions or objections!

2017-02-18 23:35 UTC, bcipolli commented on experiments/multi/slotnick_etal_2001/slotnick_figures_234.m
> +            %set(gca, 'ytick', []);
Better to just remove the code, since it's not in source control.

2017-02-18 23:35 UTC, bcipolli commented on experiments/multi/slotnick_etal_2001/slotnick_figures_234.m
> +            left_temp = [left{1}, left{2}];
Please add a comment that `1` and `2` are referring to the conditions in the task.

2017-02-18 23:35 UTC, bcipolli commented on experiments/34x25/slotnick_etal_2001/uber_slotnick_pairedsquares_coordinate.m
> +tst.stats.rej.cc.anova.test.stats
Doing this here will cause errors if the stats/plots change. Can we just have this dumped wherever this is computed? Then it's only in a single place, and only runs if the stat is computed.

2017-02-18 23:35 UTC, bcipolli commented on code/stim/de_MakeDataset.m
> +        opt = {opt{1}};
Haha making this kind of change is gonna be sooo hard to track down. There's gotta be a way to do this...

2017-02-18 23:35 UTC, bcipolli commented on code/_expts/slotnick_etal_2001/analyze/plots/de_PlotGroupBasicsSlot.m
> +                                     taskTitle, stimSet, runs,runs, ax(tai));
This is only correct if there have been no model rejections. These should either use the # of models, or just pass a single parameter.

2017-02-18 23:35 UTC, bcipolli commented on code/_expts/slotnick_etal_2001/analyze/plots/de_CreateSlotnickFigure1.m
> +    yrule.FontSize=15
mmmm I doubt this is compatible with my version of MATLAB, and inconsistent with what we do elsewhere. I'd rather see `ylabel('blah', 'fontsize', 15);` or `set(gca, 'FontSize', 15);`

2017-02-18 23:42 UTC, vishaalprasad commented on code/stim/de_MakeDataset.m
> +        opt = {opt{1}};
Yeah I'll delete that, I didn't really mean for it to get committed lol.

2017-02-18 23:43 UTC, vishaalprasad commented on experiments/34x25/slotnick_etal_2001/uber_slotnick_pairedsquares_coordinate.m
> +tst.stats.rej.cc.anova.test.stats
It's fine. It makes sense to only show that information if it is explicitly asked for.

2017-02-19 02:07 UTC, vishaalprasad commented on code/_expts/slotnick_etal_2001/analyze/plots/de_CreateSlotnickFigure1.m
> +    yrule.FontSize=15
That changes the size of the labels, which I don't care about. I want to change the size of the YTickLabels and that seems to be the only way to do it. [You are right though, it was a feature introduced in 2015B ](https://www.mathworks.com/matlabcentral/answers/298117-independent-xticklabel-and-yticklabel-font-sizes)

Not really sure what the solution is. I can comment it out and put a note there.

2017-02-25 21:26 UTC, bcipolli approved these changes

2017-02-25 21:26 UTC, merged